extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings

plugins:
  - import

env:
  es6: true
  node: true

parserOptions:
  ecmaVersion: 6
  sourceType:  module

rules:
  indent:
    - "error"
    - "tab"
    -
      SwitchCase:  1
  semi:
    - "error"
    - "always"
  comma-dangle:
    - "error"
    - "never"
  require-jsdoc:
    - "error"
    -
      require:
        MethodDefinition: true
        ClassDeclaration: true
        ArrowFunctionExpression: false
        FunctionDeclaration: true
  valid-jsdoc:
    - "error"
    -
      prefer:
        returns: return
        augments: extends
